steps:
  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/praktikum-tcc-133/my-php-app", "."]

  # Push the Docker image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/praktikum-tcc-133/my-php-app"]

  # Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - "run"
      - "deploy"
      - "my-php-app"
      - "--image=gcr.io/praktikum-tcc-133/my-php-app"
      - "--platform=managed"
      - "--region=us-central1"
